### ISSUE TITLE
Engineer Turret entitties

### ISSUE THREAD

**Issue by hrafnbrand** [DestroyedClone/AncientScepter#14]
Having trouble with SAAS, in that when playing Engineer, upon picking up the item the Turret (TR-12) limit does not increase to 3. This results in the item being almost 100% useless, as the only benefit is RNG red items on turrets.

**Comment by DestroyedClone** [comment]
What is "SAAS"?

**Comment by DestroyedClone** [comment]
Ah, Stand__A__lone Ancient Scepter. Well I just tried it right now with Lysate Cell too, and they all work as expected. Unable to replicate.
