### ISSUE TITLE
Scepter's having issues with Mostly Tame Mimic (Tinker's Satchel)

### ISSUE THREAD

**Issue by Mohl97** [DestroyedClone/AncientScepter#17]
I had my ancient scepter get rerolled by mimic today, went to report it on the tinker's satchel github, closed said report after finding out it was supposedly fixed on scepter's end, and am here to say that something's broken again and Ancient Scepter is rerolling itself when a mimic decides to turn into scepter.

It's definitely not a case of me having an outdated version either, as I can see the tiler2 blacklist call in dnspy on my installation.

**Comment by DestroyedClone** [comment]
https://github.com/DestroyedClone/AncientScepter/commit/d0962f71eddce5e3b20aa6eb1df9aa8175a7071f Not sure why it was commented out, but it should be in the next release.
