### ISSUE TITLE
Starting a second run after your first stops enemies from spawning, fixed by disabling Ancient Scepter

### ISSUE THREAD

**Issue by TrueMemeKing** [DestroyedClone/AncientScepter#33]
[LogOutput.log](https://github.com/DestroyedClone/AncientScepter/files/10422846/LogOutput.log)
Here is the log, first run spawns enemies no problem, but going back to menu and starting another permanently stops enemies from spawning. Ancient Scepter throws an error on re-entering the menu.

**Comment by ggang-b** [comment]
So do I. This problem occurs immediately when using Risky_Lives' Risky mod together. All enemies are not sponged, occasionally starting and not even being able to leave the rover.

**Comment by yekoc** [comment]
Should be fixed in the latest release
