### ISSUE TITLE
Replaced Skill Regen Too Quick On All Replaced Skills

### ISSUE THREAD

**Issue by Jarthuzad** [DestroyedClone/AncientScepter#40]
Tested with no mods but the base mods and debug toolkit (and Ancient Scepter of course)

Sometimes (seems to relate to kills?), the skill replaced by the scepter will recharge soon than intended, with the cool-down not representing said recharge (i.e 6 seconds left but then recharges). Having more (unique?) items seems to make it easier to trigger, but no specific item seems to cause it. It can get to the point the recharge is (near) instant and can be spammed excessively.

I can't seem anywhere to show that this is intentional, so if I'm wrong please let me know.

**Comment by yekoc** [comment]
The version before this one had a bug that could cause something that looks like this but should be fixed.
Can you confirm that this still happens on the latest version (1.1.31)?

**Comment by Jarthuzad** [comment]
It does occur on the latest version still, I'm not sure what causes it at all, but my log and a video are provided below (a video of it not occurring early game, and one of it occurring late game)
[https://www.youtube.com/watch?v=AvMgBG-7j7U](url)
[https://www.youtube.com/watch?v=X1EIq5XLR2U](url)
[LogOutput.log](https://github.com/DestroyedClone/AncientScepter/files/13061895/LogOutput.log)

**Comment by Jarthuzad** [comment]
mistakenly clicked close

**Comment by yekoc** [comment]
Should be fixed in 6b65b33 (and thus in the latest thunderstore release), thanks for the report as well as the extra information.
Please re-open if issue persists.

**Comment by Jarthuzad** [comment]
no problem man, i was hoping the update fixed it but when i noticed it didn't i thought i'd post this lol.
thanks for fixin' it
