### ISSUE TITLE
Loader's Charged Gauntlet and Thunder Gauntlet not granting barrier

### ISSUE THREAD

**Issue by Feathertoes** [DestroyedClone/AncientScepter#46]
This mod seems to interact strangely with her base shift abilities and removes the vanilla behavior of granting 5% of max health in barrier on hit with her punching abilities. I hope this can get resolved soon, she's the goat and I love this mod but it makes her hard to play on inferno

https://github.com/DestroyedClone/AncientScepter/assets/70271757/e0656cac-4389-434b-9b58-355376b8c027

**Comment by DestroyedClone** [comment]
Found the cause, there is a missing orig() call
https://github.com/DestroyedClone/AncientScepter/blob/8cee7fcfab193b28ed5f82c46cc97acb8decc696/AncientScepter/ScepterSkills/LoaderChargeFist2.cs#L79-L88

**Comment by Feathertoes** [comment]
any guesses on when a fix can be implemented? just curious, like the mod a lot
